# Generated by Django 5.0.6 on 2024-06-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='position',
            field=models.CharField(choices=[(1, 'پشتیبان'), (2, 'ثبت کالا'), (3, 'حسابدار'), (4, 'پست کالا')], max_length=50, verbose_name='سمت و پست کارمند'),
        ),
    ]
