# Generated by Django 5.0.6 on 2024-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_alter_usermodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='position',
            field=models.IntegerField(choices=[(1, 'پشتیبان'), (2, 'ثبت کالا'), (3, 'حسابدار'), (4, 'پست کالا')], verbose_name='سمت و پست کارمند'),
        ),
    ]
