# Generated by Django 5.0.6 on 2024-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_alter_usermodel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='number',
            field=models.IntegerField(default=1, verbose_name='تعداد محصول'),
        ),
    ]
