# Generated by Django 5.0.6 on 2024-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0005_alter_usermodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'مدیر'), (2, 'پشتیبان'), (3, 'ثبت کالا'), (4, 'حسابدار'), (5, 'پست کالا')], null=True, verbose_name='سمت و پست کارمند'),
        ),
    ]
