# Generated by Django 5.0.6 on 2024-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0007_ticketmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='state',
            field=models.IntegerField(null=True, verbose_name='وضعیت تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='send',
            field=models.IntegerField(verbose_name='کاربر ارسال کننده پیام'),
        ),
    ]
