# Generated by Django 5.0.6 on 2024-06-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_ticketmodel_state_alter_ticketmodel_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='state',
            field=models.IntegerField(verbose_name='وضعیت تیکت'),
        ),
    ]
