# Generated by Django 5.0.6 on 2024-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0009_alter_ticketmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='state',
            field=models.IntegerField(default=0, verbose_name='وضعیت تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='text',
            field=models.TextField(verbose_name='متن تیکت'),
        ),
    ]
