# Generated by Django 5.0.6 on 2024-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0010_alter_ticketmodel_state_alter_ticketmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='موضوع تیکت'),
        ),
    ]
