# Generated by Django 5.0.6 on 2024-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0011_ticketmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='receive',
            field=models.IntegerField(verbose_name='کاربر دریافت کننده پیام'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='state',
            field=models.IntegerField(default=1, verbose_name='وضعیت تیکت'),
        ),
    ]
