# Generated by Django 5.0.6 on 2024-06-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0015_alter_productmodel_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='is_sale',
            field=models.BooleanField(blank=True, verbose_name='محصول دارای تخفیف'),
        ),
    ]
