# Generated by Django 5.0.6 on 2024-06-29 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0017_alter_productmodel_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayTicketModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raplay_text', models.TextField(verbose_name='متن ریپلای')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.ticketmodel', verbose_name='تیکت')),
            ],
        ),
    ]
