# Generated by Django 5.0.6 on 2024-07-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0018_replayticketmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
