# Generated by Django 5.0.6 on 2024-07-03 02:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0019_pageviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='satisfaction',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان رضایت از محصول'),
        ),
        migrations.CreateModel(
            name='SatisfactionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('satisfaction', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان رضایت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رضایت از محصول',
                'verbose_name_plural': 'رضایت از محصولات',
            },
        ),
    ]
