# Generated by Django 5.0.6 on 2024-07-03 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0020_productmodel_satisfaction_satisfactionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeLikeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(verbose_name='لایک')),
                ('Dislike', models.IntegerField(verbose_name='دیس\u200cلایک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک و دیس\u200cلایک محصول',
                'verbose_name_plural': 'لایک و دیس\u200cلایک محصولات',
            },
        ),
    ]
