# Generated by Django 5.0.6 on 2024-07-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0021_dislikelikemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
