# Generated by Django 5.0.6 on 2024-07-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0022_delete_likemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikelikemodel',
            name='Dislike',
        ),
        migrations.AddField(
            model_name='dislikelikemodel',
            name='dis_like',
            field=models.IntegerField(default=0, verbose_name='دیس\u200cلایک'),
        ),
        migrations.AlterField(
            model_name='dislikelikemodel',
            name='like',
            field=models.IntegerField(default=0, verbose_name='لایک'),
        ),
    ]
