# Generated by Django 5.0.6 on 2024-07-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0023_remove_dislikelikemodel_dislike_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DislikeLikeModel',
        ),
    ]
