# Generated by Django 5.0.6 on 2024-07-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0024_delete_dislikelikemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='text_comment',
            new_name='comment_text',
        ),
    ]
