# Generated by Django 5.0.6 on 2024-07-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0025_rename_text_comment_commentmodel_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayCommentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(verbose_name='متن نظر')),
                ('published_comment', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.commentmodel', verbose_name='نظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ریپلای نظر',
                'verbose_name_plural': 'ریپلای نظرات',
            },
        ),
    ]
