# Generated by Django 5.0.6 on 2024-07-07 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0026_replaycommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='disLikeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disLike', models.IntegerField(verbose_name='دیس لایک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='likeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(verbose_name='لایک')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
