# Generated by Django 5.0.6 on 2024-07-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0027_dislikemodel_likemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='satisfaction',
        ),
    ]
