# Generated by Django 5.0.6 on 2024-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0028_remove_productmodel_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidermodel',
            name='price',
            field=models.IntegerField(null=True, verbose_name='قیمت محصول'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='sale_price',
            field=models.IntegerField(null=True, verbose_name='تخفیف محصول'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان اسلایدر'),
        ),
    ]
