# Generated by Django 5.0.6 on 2024-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0029_slidermodel_price_slidermodel_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayticketmodel',
            name='sender',
            field=models.IntegerField(null=True, verbose_name='ارسال کننده'),
        ),
    ]
