# Generated by Django 5.0.6 on 2024-08-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0030_replayticketmodel_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='GalleryProduct/', verbose_name='تصویر محصولات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.productmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
