# Generated by Django 5.0.6 on 2024-08-22 15:49

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0031_galleryproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='published_comment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
