# Generated by Django 5.0.6 on 2024-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0034_alter_commentmodel_published_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=80, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='province',
            field=models.CharField(max_length=50, null=True, verbose_name='استان'),
        ),
    ]
