# Generated by Django 5.0.6 on 2024-09-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0035_usermodel_city_usermodel_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='factormodel',
            name='is_factor',
            field=models.IntegerField(choices=[(0, 'بله'), (1, 'نه')], null=True),
        ),
    ]
