# Generated by Django 5.0.6 on 2024-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0036_factormodel_is_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factormodel',
            name='is_factor',
            field=models.IntegerField(null=True, verbose_name='صادر کردن فاکتور'),
        ),
    ]
