# Generated by Django 5.0.6 on 2024-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0037_alter_factormodel_is_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200, verbose_name='متن تبلیغات')),
                ('image', models.ImageField(upload_to='advertisingImage/', verbose_name='عکس تبلیغات')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تبلیغات')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
            ],
        ),
    ]
