# Generated by Django 5.0.6 on 2024-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0038_advertisingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
