# Generated by Django 5.0.6 on 2024-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0039_productmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='replayticketmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
