# Generated by Django 5.0.6 on 2024-09-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0040_replayticketmodel_created_ticketmodel_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replayticketmodel',
            old_name='raplay_text',
            new_name='replay_text',
        ),
    ]
