# Generated by Django 5.0.6 on 2024-09-06 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0041_rename_raplay_text_replayticketmodel_replay_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replayticketmodel',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده'),
        ),
    ]
