# Generated by Django 5.0.6 on 2024-09-06 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0042_alter_replayticketmodel_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع تاریخ')),
                ('end_date', models.DateTimeField(verbose_name='پایان تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن تخفیف')),
            ],
        ),
    ]
