# Generated by Django 5.0.6 on 2024-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0043_discountcodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodemodel',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف'),
        ),
    ]
