# Generated by Django 5.0.6 on 2024-09-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0044_alter_discountcodemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodemodel',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
    ]
