# Generated by Django 5.0.6 on 2024-09-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0045_alter_discountcodemodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcodemodel',
            old_name='code',
            new_name='discount_code',
        ),
    ]
