# Generated by Django 5.0.6 on 2024-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0046_rename_code_discountcodemodel_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodemodel',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='توضیحات'),
        ),
    ]
