# Generated by Django 5.0.6 on 2024-09-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0047_discountcodemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت کننده پیام'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال کننده پیام'),
        ),
    ]
