# Generated by Django 5.0.6 on 2024-09-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
        ('myShop', '0049_remove_factormodel_product_factorproduct_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactorProduct',
            new_name='FactorProductModel',
        ),
        migrations.AddField(
            model_name='factormodel',
            name='bank_transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='azbankgateways.bank', verbose_name='تراکنش بانکی'),
        ),
    ]
