# Generated by Django 5.0.6 on 2024-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0050_rename_factorproduct_factorproductmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='aboutImage/', verbose_name='تصویر کاربر')),
                ('description', models.TextField(verbose_name='توضیح کاربر')),
            ],
        ),
    ]
