# Generated by Django 5.0.6 on 2024-09-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0051_aboutmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='description',
            new_name='about',
        ),
    ]
