# Generated by Django 5.0.6 on 2024-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0052_rename_description_aboutmodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertisingImage/', verbose_name='عکس تبلیغات'),
        ),
    ]
