# Generated by Django 5.0.6 on 2024-09-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0054_alter_productmodel_category_alter_productmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myShop.categorymodel', verbose_name='دسته بندی محصول'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='number',
            field=models.IntegerField(default=1, verbose_name='تعداد محصول'),
        ),
    ]
