# Generated by Django 5.0.6 on 2024-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0055_alter_productmodel_category_alter_productmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='right',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True, verbose_name='حقوق'),
        ),
    ]
