# Generated by Django 5.0.6 on 2024-09-29 08:42

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0056_usermodel_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcodemodel',
            name='end_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='آدرس'),
        ),
    ]
