# Generated by Django 5.0.6 on 2024-10-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0060_alter_productmodel_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderModel',
        ),
    ]
